---
- name: make sure docker-python RPM is not installed
  yum:
    name: docker-python
    state: absent

- name: make sure required PyPi packages are installed
  pip:
    name: '{{ item }}'
    state: present
  with_items: 
    - docker-py==1.2.3
    - six>=1.4.0

# tasks file for kafka-monitor
- name: kafka-monitor
  docker:
    name: kafka-monitor
    image: akursar/kafkaoffsetmonitor
    state: "{{kafka_monitor_state}}"
    restart_policy: always
    net: host
    ports:
      - "9001:9001"
    env:
      ZK_HOSTS: "{{zk_kafka_path}}"
      PORT: "9001"
      RETAIN_DAYS: "7"

